name: smart_water_systerm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
   flutter:
    sdk: flutter
   firebase_core: ^2.0.0
   firebase_database: ^10.0.6
   google_fonts: ^6.0.0
   percent_indicator: ^4.2.3
   fl_chart: ^0.63.0 
   firebase_auth: ^4.16.0
   google_sign_in: ^6.3.0
   
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/google.png